plugins {
	id 'java'
	id 'org.springframework.boot' version '4.0.8'
	id 'io.spring.dependency-management' version '1.1.7'
	id 'com.diffplug.spotless' version '6.25.0'
	id 'org.owasp.dependencycheck' version '12.2.2'
}

group = 'io.github.jantrw'
version = '0.0.1-SNAPSHOT'
description = 'Car Fuel Live backend'

ext['jackson-2-bom.version'] = '2.21.5'
ext['jackson-bom.version'] = '3.1.5'
ext['log4j2.version'] = '2.25.5'
ext['postgresql.version'] = '42.7.13'
ext['tomcat.version'] = '11.0.26'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

spotless {
	java {
		googleJavaFormat('1.22.0')
		removeUnusedImports()
		trimTrailingWhitespace()
		endWithNewline()
	}
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-security'
	implementation 'org.springframework.boot:spring-boot-starter-webmvc'
	implementation 'org.springframework.boot:spring-boot-starter-jdbc'
	implementation 'org.springframework.boot:spring-boot-starter-validation'
	implementation("org.springdoc:springdoc-openapi-starter-webmvc-ui:3.1.1")
	implementation 'org.springframework.boot:spring-boot-starter-flyway'
	developmentOnly 'org.springframework.boot:spring-boot-devtools'
	developmentOnly 'org.springframework.boot:spring-boot-docker-compose'
	runtimeOnly 'org.postgresql:postgresql'
	runtimeOnly 'org.flywaydb:flyway-database-postgresql:11.14.1'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
	testImplementation 'org.springframework.boot:spring-boot-testcontainers'
	testImplementation platform('org.testcontainers:testcontainers-bom:2.0.4')
	testImplementation 'org.testcontainers:testcontainers-junit-jupiter'
	testImplementation 'org.testcontainers:testcontainers-postgresql'
	testImplementation 'com.h2database:h2'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform();
	spotlessJavaCheck;
}

dependencyCheck {
	failBuildOnCVSS = 7
	skipConfigurations = ['developmentOnly']
	nvd {
		apiKey = System.getenv('NVD_API_KEY')
		validForHours = 48
	}
}
